import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';
import 'package:get_hooked/listenables.dart';
import 'package:get_hooked/src/ref_element.dart';

/// Signature for the callback passed to [RefShaderMask].
typedef RefShaderCallback = Shader Function(ShaderRef ref);

/// Interface used in the [RefShaderCallback].
abstract interface class ShaderRef implements Ref {
  /// The [Rect] used to create a [Shader].
  abstract final Rect bounds;
}

/// A variant of [ShaderMask] that evaluates based on a [RefComputer<Shader>].
class RefShaderMask extends SingleChildRenderObjectWidget {
  /// Creates an [Padding] widget using the provided [RefShaderCallback].
  const RefShaderMask(this.createShader, {super.key, this.blendMode = .modulate, super.child});

  /// The amount of space by which to inset the child.
  final RefShaderCallback createShader;

  /// The [BlendMode] to use when applying the shader to the child.
  ///
  /// The default, [BlendMode.modulate], is useful for applying an alpha blend
  /// to the child. Other blend modes can be used to create other effects.
  final BlendMode blendMode;

  @override
  RenderObject createRenderObject(BuildContext context) {
    context as _ShaderMaskElement;
    return _RenderRefShaderMask(
      getShader: () => (context.widget as RefShaderMask).createShader(context),
      setBounds: (rect) => context.bounds = rect,
      blendMode: blendMode,
    );
  }

  @override
  void updateRenderObject(BuildContext context, RenderObject renderObject) {
    (renderObject as _RenderRefShaderMask).blendMode = blendMode;
  }

  @override
  SingleChildRenderObjectElement createElement() => _ShaderMaskElement(this);
}

class _ShaderMaskElement extends SingleChildComputeElement<_RenderRefShaderMask>
    implements ShaderRef {
  _ShaderMaskElement(super.widget);

  @override
  late Rect bounds;

  @override
  void recompute() => renderer.markNeedsPaint();
}

/// Applies a mask generated by a [Shader] to its child.
class _RenderRefShaderMask extends RenderProxyBox {
  /// Creates a render object that applies a mask generated by a [Shader] to its child.
  _RenderRefShaderMask({
    required this._getShader,
    required this._setBounds,
    required this._blendMode,
  }) : super(null);

  @override
  ShaderMaskLayer? get layer => super.layer as ShaderMaskLayer?;

  final ValueGetter<Shader> _getShader;
  final ValueSetter<Rect> _setBounds;

  BlendMode get blendMode => _blendMode;
  BlendMode _blendMode;
  set blendMode(BlendMode value) {
    if (value == _blendMode) return;
    _blendMode = value;
    markNeedsPaint();
  }

  @override
  bool get alwaysNeedsCompositing => child != null;

  @override
  void paint(PaintingContext context, Offset offset) {
    if (child != null) {
      assert(needsCompositing);
      _setBounds(Offset.zero & size);
      final layer = (this.layer ??= ShaderMaskLayer())
        ..shader = _getShader()
        ..maskRect = offset & size
        ..blendMode = _blendMode;
      context.pushLayer(layer, super.paint, offset);
      if (kDebugMode) layer.debugCreator = debugCreator;
    } else {
      layer = null;
    }
  }
}
