name: get_hooked
description: "inspired by get_it, uses flutter_hooks"
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  collection_notifiers: ^1.1.0
  flutter_hooks: ">=0.18.5 <1.0.0"
  meta: ">=1.10.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0"

flutter:
  uses-material-design: true
