name: get_hooked
description: "inspired by get_it, uses flutter_hooks"
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  collection_notifiers: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0"

flutter:
  uses-material-design: true
