name: get_hooked
description: "Shared state with flutter_hooks! Inspired by riverpod and get_it."
version: 0.1.0
homepage: https://no-tolls.dev/
issue_tracker: https://github.com/nate-thegrate/get_hooked/issues
repository: https://github.com/nate-thegrate/get_hooked/tree/main/packages/get_hooked
topics:
  - flutter
  - animation
  - state-management

environment:
  sdk: '>=3.7.0-123.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  collection_notifiers: ^1.1.0
  flutter_hooks: ">=0.18.5 <1.0.0"
  meta: ">=1.10.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0"

flutter:
  uses-material-design: true
