import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';

import 'signal_element.dart';

/// Signature for the callback passed to [SignalShaderMask].
typedef SignalShaderCallback = Shader Function(BuildContext context, Rect bounds);

/// A variant of [ShaderMask] that evaluates based on a [SignalShaderCallback].
class SignalShaderMask extends SingleChildRenderObjectWidget {
  /// Creates a [ShaderMask] widget using the provided [SignalShaderCallback].
  const SignalShaderMask(
    this.createShader, {
    super.key,
    this.blendMode = BlendMode.modulate,
    super.child,
  });

  /// Called to create the [Shader] each time the mask is painted.
  ///
  /// Signals read via `.value` during this callback are tracked; when they
  /// change, the mask repaints without rebuilding the child.
  final SignalShaderCallback createShader;

  /// The [BlendMode] to use when applying the shader to the child.
  ///
  /// The default, [BlendMode.modulate], is useful for applying an alpha blend
  /// to the child. Other blend modes can be used to create other effects.
  final BlendMode blendMode;

  @override
  RenderObject createRenderObject(BuildContext context) {
    context as _ShaderMaskElement;
    return _RenderSignalShaderMask(
      getShader: context.evaluateShader,
      setBounds: (rect) => context.bounds = rect,
      blendMode: blendMode,
    );
  }

  @override
  void updateRenderObject(BuildContext context, RenderObject renderObject) {
    (renderObject as _RenderSignalShaderMask).blendMode = blendMode;
  }

  @override
  SingleChildRenderObjectElement createElement() => _ShaderMaskElement(this);
}

class _ShaderMaskElement extends SingleChildSignalElement<_RenderSignalShaderMask> {
  _ShaderMaskElement(super.widget);

  Rect bounds = Rect.zero;

  /// Creates the shader for the current [bounds].
  ///
  /// Signal subscriptions are established in [recompute], not here, so paint
  /// does not clear watches after a signal-driven repaint.
  Shader evaluateShader() {
    return (widget as SignalShaderMask).createShader(this, bounds);
  }

  @override
  void recompute() {
    // Evaluate once to track `.value` reads; paint will create the final shader.
    (widget as SignalShaderMask).createShader(this, bounds);
    renderer.markNeedsPaint();
  }
}

/// Applies a mask generated by a [Shader] to its child.
class _RenderSignalShaderMask extends RenderProxyBox {
  /// Creates a render object that applies a mask generated by a [Shader] to its child.
  _RenderSignalShaderMask({
    required this._getShader,
    required this._setBounds,
    required this._blendMode,
  }) : super(null);

  @override
  ShaderMaskLayer? get layer => super.layer as ShaderMaskLayer?;

  final ValueGetter<Shader> _getShader;
  final ValueSetter<Rect> _setBounds;

  BlendMode get blendMode => _blendMode;
  BlendMode _blendMode;
  set blendMode(BlendMode value) {
    if (value == _blendMode) return;
    _blendMode = value;
    markNeedsPaint();
  }

  @override
  bool get alwaysNeedsCompositing => child != null;

  @override
  void paint(PaintingContext context, Offset offset) {
    if (child != null) {
      assert(needsCompositing);
      _setBounds(Offset.zero & size);
      final layer = (this.layer ??= ShaderMaskLayer())
        ..shader = _getShader()
        ..maskRect = offset & size
        ..blendMode = _blendMode;
      context.pushLayer(layer, super.paint, offset);
      if (kDebugMode) layer.debugCreator = debugCreator;
    } else {
      layer = null;
    }
  }
}
