# more info: https://dart.dev/guides/language/analysis-options
# all rules: https://dart.dev/tools/linter-rules,
#            https://github.com/dart-lang/sdk/blob/main/pkg/linter/example/all.yaml

include: ../analysis_options.yaml

# formatter:
#   page_width: 80

linter:
  rules:
    public_member_api_docs: false
